image: node:20

before_script:
  - yarn

stages:
  - build
  - doc-deploy
  - ui-tests

build:
  stage: build
  script:   
    - yarn run lint
    - yarn build
  artifacts:
    paths:
      - dist

functional-tests:
  stage: ui-tests
  dependencies: [build]
  script:
    - ./tests/test-server.sh
    - yarn
    - npx playwright install-deps &> /dev/null
    - npx playwright install
    - yarn test
  artifacts:
    when: always
    paths:
      - test-results/.last-run.json
      - playwright-report/index.html

ui-tests:
  stage: ui-tests
  script:
    - apt-get -qqy update > /dev/null 2> /dev/null
    - apt-get -qqy install --no-install-recommends chromium > /dev/null 2> /dev/null
    - yarn run dev&
    - node bin/server.js&
    - yarn run ui-test
  artifacts:
    when: always
    paths:
      - ui-tests/*.png

doc-deploy:
  stage: doc-deploy
  tags: ["docs"]
  dependencies: [build]
  script:
    - sed -i -e 's/{}.VITE_COLLAB/"ON"/g' dist/index.js
    - sed -i -e 's/{}.VITE_WS_URL/"\/devsignal"/g' dist/index.js
    - tar cf $CI_DOCS_ARCHIVE -C dist/ .
  artifacts:
    paths:
      - docs.tar
  only:
    - merge_requests